/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVehiculosRouteImport } from './routes/_authenticated/vehiculos'
import { Route as AuthenticatedInformesRouteImport } from './routes/_authenticated/informes'
import { Route as AuthenticatedDocumentacionRouteImport } from './routes/_authenticated/documentacion'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConduccionRouteImport } from './routes/_authenticated/conduccion'
import { Route as AuthenticatedJesusRouteRouteImport } from './routes/_authenticated/jesus/route'
import { Route as AuthenticatedJesusPendientesRouteImport } from './routes/_authenticated/jesus/pendientes'
import { Route as AuthenticatedJesusMultasRouteImport } from './routes/_authenticated/jesus/multas'
import { Route as AuthenticatedJesusDocumentacionRouteImport } from './routes/_authenticated/jesus/documentacion'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVehiculosRoute = AuthenticatedVehiculosRouteImport.update({
  id: '/vehiculos',
  path: '/vehiculos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInformesRoute = AuthenticatedInformesRouteImport.update({
  id: '/informes',
  path: '/informes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentacionRoute =
  AuthenticatedDocumentacionRouteImport.update({
    id: '/documentacion',
    path: '/documentacion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConduccionRoute = AuthenticatedConduccionRouteImport.update({
  id: '/conduccion',
  path: '/conduccion',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJesusRouteRoute = AuthenticatedJesusRouteRouteImport.update({
  id: '/jesus',
  path: '/jesus',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJesusPendientesRoute =
  AuthenticatedJesusPendientesRouteImport.update({
    id: '/pendientes',
    path: '/pendientes',
    getParentRoute: () => AuthenticatedJesusRouteRoute,
  } as any)
const AuthenticatedJesusMultasRoute =
  AuthenticatedJesusMultasRouteImport.update({
    id: '/multas',
    path: '/multas',
    getParentRoute: () => AuthenticatedJesusRouteRoute,
  } as any)
const AuthenticatedJesusDocumentacionRoute =
  AuthenticatedJesusDocumentacionRouteImport.update({
    id: '/documentacion',
    path: '/documentacion',
    getParentRoute: () => AuthenticatedJesusRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/jesus': typeof AuthenticatedJesusRouteRouteWithChildren
  '/conduccion': typeof AuthenticatedConduccionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentacion': typeof AuthenticatedDocumentacionRoute
  '/informes': typeof AuthenticatedInformesRoute
  '/vehiculos': typeof AuthenticatedVehiculosRoute
  '/jesus/documentacion': typeof AuthenticatedJesusDocumentacionRoute
  '/jesus/multas': typeof AuthenticatedJesusMultasRoute
  '/jesus/pendientes': typeof AuthenticatedJesusPendientesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/jesus': typeof AuthenticatedJesusRouteRouteWithChildren
  '/conduccion': typeof AuthenticatedConduccionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentacion': typeof AuthenticatedDocumentacionRoute
  '/informes': typeof AuthenticatedInformesRoute
  '/vehiculos': typeof AuthenticatedVehiculosRoute
  '/jesus/documentacion': typeof AuthenticatedJesusDocumentacionRoute
  '/jesus/multas': typeof AuthenticatedJesusMultasRoute
  '/jesus/pendientes': typeof AuthenticatedJesusPendientesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/jesus': typeof AuthenticatedJesusRouteRouteWithChildren
  '/_authenticated/conduccion': typeof AuthenticatedConduccionRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentacion': typeof AuthenticatedDocumentacionRoute
  '/_authenticated/informes': typeof AuthenticatedInformesRoute
  '/_authenticated/vehiculos': typeof AuthenticatedVehiculosRoute
  '/_authenticated/jesus/documentacion': typeof AuthenticatedJesusDocumentacionRoute
  '/_authenticated/jesus/multas': typeof AuthenticatedJesusMultasRoute
  '/_authenticated/jesus/pendientes': typeof AuthenticatedJesusPendientesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/jesus'
    | '/conduccion'
    | '/dashboard'
    | '/documentacion'
    | '/informes'
    | '/vehiculos'
    | '/jesus/documentacion'
    | '/jesus/multas'
    | '/jesus/pendientes'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/jesus'
    | '/conduccion'
    | '/dashboard'
    | '/documentacion'
    | '/informes'
    | '/vehiculos'
    | '/jesus/documentacion'
    | '/jesus/multas'
    | '/jesus/pendientes'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/jesus'
    | '/_authenticated/conduccion'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentacion'
    | '/_authenticated/informes'
    | '/_authenticated/vehiculos'
    | '/_authenticated/jesus/documentacion'
    | '/_authenticated/jesus/multas'
    | '/_authenticated/jesus/pendientes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vehiculos': {
      id: '/_authenticated/vehiculos'
      path: '/vehiculos'
      fullPath: '/vehiculos'
      preLoaderRoute: typeof AuthenticatedVehiculosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/informes': {
      id: '/_authenticated/informes'
      path: '/informes'
      fullPath: '/informes'
      preLoaderRoute: typeof AuthenticatedInformesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentacion': {
      id: '/_authenticated/documentacion'
      path: '/documentacion'
      fullPath: '/documentacion'
      preLoaderRoute: typeof AuthenticatedDocumentacionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conduccion': {
      id: '/_authenticated/conduccion'
      path: '/conduccion'
      fullPath: '/conduccion'
      preLoaderRoute: typeof AuthenticatedConduccionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jesus': {
      id: '/_authenticated/jesus'
      path: '/jesus'
      fullPath: '/jesus'
      preLoaderRoute: typeof AuthenticatedJesusRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jesus/pendientes': {
      id: '/_authenticated/jesus/pendientes'
      path: '/pendientes'
      fullPath: '/jesus/pendientes'
      preLoaderRoute: typeof AuthenticatedJesusPendientesRouteImport
      parentRoute: typeof AuthenticatedJesusRouteRoute
    }
    '/_authenticated/jesus/multas': {
      id: '/_authenticated/jesus/multas'
      path: '/multas'
      fullPath: '/jesus/multas'
      preLoaderRoute: typeof AuthenticatedJesusMultasRouteImport
      parentRoute: typeof AuthenticatedJesusRouteRoute
    }
    '/_authenticated/jesus/documentacion': {
      id: '/_authenticated/jesus/documentacion'
      path: '/documentacion'
      fullPath: '/jesus/documentacion'
      preLoaderRoute: typeof AuthenticatedJesusDocumentacionRouteImport
      parentRoute: typeof AuthenticatedJesusRouteRoute
    }
  }
}

interface AuthenticatedJesusRouteRouteChildren {
  AuthenticatedJesusDocumentacionRoute: typeof AuthenticatedJesusDocumentacionRoute
  AuthenticatedJesusMultasRoute: typeof AuthenticatedJesusMultasRoute
  AuthenticatedJesusPendientesRoute: typeof AuthenticatedJesusPendientesRoute
}

const AuthenticatedJesusRouteRouteChildren: AuthenticatedJesusRouteRouteChildren =
  {
    AuthenticatedJesusDocumentacionRoute: AuthenticatedJesusDocumentacionRoute,
    AuthenticatedJesusMultasRoute: AuthenticatedJesusMultasRoute,
    AuthenticatedJesusPendientesRoute: AuthenticatedJesusPendientesRoute,
  }

const AuthenticatedJesusRouteRouteWithChildren =
  AuthenticatedJesusRouteRoute._addFileChildren(
    AuthenticatedJesusRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedJesusRouteRoute: typeof AuthenticatedJesusRouteRouteWithChildren
  AuthenticatedConduccionRoute: typeof AuthenticatedConduccionRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentacionRoute: typeof AuthenticatedDocumentacionRoute
  AuthenticatedInformesRoute: typeof AuthenticatedInformesRoute
  AuthenticatedVehiculosRoute: typeof AuthenticatedVehiculosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedJesusRouteRoute: AuthenticatedJesusRouteRouteWithChildren,
  AuthenticatedConduccionRoute: AuthenticatedConduccionRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentacionRoute: AuthenticatedDocumentacionRoute,
  AuthenticatedInformesRoute: AuthenticatedInformesRoute,
  AuthenticatedVehiculosRoute: AuthenticatedVehiculosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
