/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedVehiculosRouteImport } from './routes/_authenticated/vehiculos'
import { Route as AuthenticatedInformesRouteImport } from './routes/_authenticated/informes'
import { Route as AuthenticatedDocumentacionRouteImport } from './routes/_authenticated/documentacion'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConduccionRouteImport } from './routes/_authenticated/conduccion'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVehiculosRoute = AuthenticatedVehiculosRouteImport.update({
  id: '/vehiculos',
  path: '/vehiculos',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInformesRoute = AuthenticatedInformesRouteImport.update({
  id: '/informes',
  path: '/informes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDocumentacionRoute =
  AuthenticatedDocumentacionRouteImport.update({
    id: '/documentacion',
    path: '/documentacion',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConduccionRoute = AuthenticatedConduccionRouteImport.update({
  id: '/conduccion',
  path: '/conduccion',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conduccion': typeof AuthenticatedConduccionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentacion': typeof AuthenticatedDocumentacionRoute
  '/informes': typeof AuthenticatedInformesRoute
  '/vehiculos': typeof AuthenticatedVehiculosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/conduccion': typeof AuthenticatedConduccionRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/documentacion': typeof AuthenticatedDocumentacionRoute
  '/informes': typeof AuthenticatedInformesRoute
  '/vehiculos': typeof AuthenticatedVehiculosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/conduccion': typeof AuthenticatedConduccionRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/documentacion': typeof AuthenticatedDocumentacionRoute
  '/_authenticated/informes': typeof AuthenticatedInformesRoute
  '/_authenticated/vehiculos': typeof AuthenticatedVehiculosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/conduccion'
    | '/dashboard'
    | '/documentacion'
    | '/informes'
    | '/vehiculos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/conduccion'
    | '/dashboard'
    | '/documentacion'
    | '/informes'
    | '/vehiculos'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/conduccion'
    | '/_authenticated/dashboard'
    | '/_authenticated/documentacion'
    | '/_authenticated/informes'
    | '/_authenticated/vehiculos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/vehiculos': {
      id: '/_authenticated/vehiculos'
      path: '/vehiculos'
      fullPath: '/vehiculos'
      preLoaderRoute: typeof AuthenticatedVehiculosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/informes': {
      id: '/_authenticated/informes'
      path: '/informes'
      fullPath: '/informes'
      preLoaderRoute: typeof AuthenticatedInformesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/documentacion': {
      id: '/_authenticated/documentacion'
      path: '/documentacion'
      fullPath: '/documentacion'
      preLoaderRoute: typeof AuthenticatedDocumentacionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/conduccion': {
      id: '/_authenticated/conduccion'
      path: '/conduccion'
      fullPath: '/conduccion'
      preLoaderRoute: typeof AuthenticatedConduccionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedConduccionRoute: typeof AuthenticatedConduccionRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDocumentacionRoute: typeof AuthenticatedDocumentacionRoute
  AuthenticatedInformesRoute: typeof AuthenticatedInformesRoute
  AuthenticatedVehiculosRoute: typeof AuthenticatedVehiculosRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedConduccionRoute: AuthenticatedConduccionRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDocumentacionRoute: AuthenticatedDocumentacionRoute,
  AuthenticatedInformesRoute: AuthenticatedInformesRoute,
  AuthenticatedVehiculosRoute: AuthenticatedVehiculosRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
